### ISSUE TITLE
Add brazilian translation

### ISSUE THREAD

**Issue by viveksb007** [viveksb007/easy_hacktoberfest_task#2]
Create a separate xml file just like given in the repo using the same keys and add corresponding translations for the english values.

**Comment by PratesM** [comment]
I've done some translation on these strings that can also be used on the portuguese version as they are both the same language, I'll drop them today in a couple of hours as I'm on my laptop and only had ATOM to write them down, so it's not yet saved as a .XML

**Comment by marcosstefani** [comment]
https://github.com/viveksb007/easy_hacktoberfest_task/pull/23
