### ISSUE TITLE
Add portuguese translation

### ISSUE THREAD

**Issue by viveksb007** [viveksb007/easy_hacktoberfest_task#4]
Create a separate xml file just like given in the repo using the same keys and add corresponding translations for the english values.

**Comment by marcosstefani** [comment]
want to work on this Issue.

**Comment by viveksb007** [comment]
Thanks. Go ahead :+1:

**Comment by marcosstefani** [comment]
https://github.com/viveksb007/easy_hacktoberfest_task/pull/23
